### ISSUE TITLE
How To Delete?

### ISSUE THREAD

**Issue by kazi-kaz** [wpichl/SpotifyAntiAd#1]
Is there a way to delete this? If I wanted to stop blocking ads?

**Comment by wpichl** [comment]
Yes, obviously there is.
Steps:

1. Go to C:\Windows\System32\drivers\etc\ and locate the file "hosts" which has no file extension
2. Open it in Notepad or any Editor of your choice (you have to open the Editor as Admin)
3. Delete the huge block from the hosts file. The addresses can be found [here](https://github.com/wpichl/SpotifyAntiAd/blob/master/blocklist.txt)
4. Restart Spotify, the ads should show up again.
